#!/usr/bin/ansible-playbook
---
- name: Fresh arch install setup
  hosts: localhost
  connection: local
  become_method: sudo
  become: true
  roles:
    - role: lightdm
    - role: i3wm
    - role: dev_pkgs
    - role: tune_os
    - role: sound

