- name: Install awesomewm dependencies
  with_items: "{{ awesomewm_deps }}"
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: true
 
- name: Install awesomewm packages
  with_items: "{{ awesomewm_pkgs }}"
  pacman:
    name: "{{ item }}"
    update_cache: true
 
- name: Add config to xinit
  become: false
  with_items: "{{ xinit_config }}"
  lineinfile:
    line: "{{ item }}"
    path: "$HOME/.xinitrc"
    create: yes

