- name: Install i3wm dependencies
  with_items: "{{ i3wm_deps }}"
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: true
 
- name: Install i3wm packages
  with_items: "{{ i3wm_pkgs }}"
  pacman:
    name: "{{ item }}"
    update_cache: true
 
- name: Add config to xinit
  become: false
  with_items: "{{ xinit_config }}"
  lineinfile:
    line: "{{ item }}"
    path: "$HOME/.xinitrc"
    create: yes

