- name: Install compilers/interpreters
  with_items: "{{ languages }}"
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: true

- name: Install dev tools
  with_items: "{{ dev_tools }}"
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: true

- name: Install package managers
  with_items: "{{ package_managers }}"
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: true

- name: Create go path
  become: false
  file:
    path: "{{ go_path }}"
    state: directory

- name: Create go directories
  become: false
  with_items: [ bin, pkg, src ]
  file:
    path: "{{ go_path }}/{{ item }}"
    state: directory

- name: Add gopath to env variables
  become: false
  with_items:
    - "export GOPATH={{ go_path }}"
    - "export PATH=$PATH:$GOPATH/bin"
  lineinfile:
    line: "{{ item }}"
    path: "$HOME/.bashrc"
    create: yes

- name: Ensure docker group sxists
  group:
    name: docker
    state: present

- name: Add user to docker group
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes

