- name: install lightdm
  with_items: "{{ packages }}"
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: true

- name: Install greeter
  pacman:
    name: lightdm-webkit2-greeter
    state: present
    update_cache: true

- name: Download theme repo
  become: false
  git:
    repo: "{{ theme.repo }}"
    version: "{{ theme.tag }}"
    dest: /tmp/glorious

- name: Create theme location
  file:
    path: /usr/share/lightdm-webkit/themes/glorious
    state: directory

- name: Copy theme files to location
  copy:
    src: /tmp/glorious
    dest: /usr/share/lightdm-webkit/themes/glorious

- name: Set lightdm webkit2 as the greeter
  replace:
    path: /etc/lightdm/lightdm.conf
    regexp: '\#greeter-session=example-gtk-gnome'
    replace: 'greeter-session=lightdm-webkit2-greeter'

- name: Set glorious as webkit theme
  with_items:
  - "webkit_theme=glorious"
  - "debug_mode=true"
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    line: "{{ item }}"
    insertafter: 'greeter-session=lightdm-webkit2-greeter'

- name: Enable locker
  lineinfile:
    path: /etc/lightdm/Xsession
    line: "light-locker & \n"
    insertbefore: 'exec .*'
    firstmatch: true

- name: Enable lightdm
  systemd:
    state: started
    name: lightdm
    enabled: true

