- name: install lightdm
  pacman:
    name: lightdm
    state: present
    update_cache: true

- name: Install greeter
  pacman:
    name: lightdm-webkit2-greeter
    state: present
    update_cache: true

