- name: install packages
  with_items: "{{ packages }}"
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: true

- name: Start pulseaudio as a daemon
  with_items:
  - "pulseaudio -D &"
  - "alsactl init &"
  - "\n"
  lineinfile:
    line: "{{ item }}"
    path: /etc/lightdm/Xsession
    insertbefore: 'exec .*'
    firstmatch: true

