- name: install packages
  with_items: "{{ packages }}"
  pacman:
    name: "{{ item }}"
    state: present
    update_cache: true

- name: Start pulseaudio as a daemon
  lineinfile:
    line: "pulseaudio -D & \n"
    path: /etc/lightdm/Xsession
    insertbefore: 'exec .*'
    firstmatch: true

