- name: Create base directories
  with_items: "{{ base_dirs }}"
  become: false
  file:
    path: "$HOME/{{ item }}"
    state: directory

- name: Setup desktop wallpaper
  become: false
  shell: nitrogen --set-zoom images/wallpaper.jpg
  
